spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
logging:
  level:
    com.zaxxer.hikari: DEBUG
